/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CgiRouteImport } from './routes/cgi'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadershipIndexRouteImport } from './routes/leadership.index'
import { Route as LeadershipSlugRouteImport } from './routes/leadership.$slug'

const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CgiRoute = CgiRouteImport.update({
  id: '/cgi',
  path: '/cgi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipIndexRoute = LeadershipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadershipRoute,
} as any)
const LeadershipSlugRoute = LeadershipSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LeadershipRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/cgi': typeof CgiRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRoute
  '/leadership': typeof LeadershipRouteWithChildren
  '/leadership/$slug': typeof LeadershipSlugRoute
  '/leadership/': typeof LeadershipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/cgi': typeof CgiRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRoute
  '/leadership/$slug': typeof LeadershipSlugRoute
  '/leadership': typeof LeadershipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/cgi': typeof CgiRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRoute
  '/leadership': typeof LeadershipRouteWithChildren
  '/leadership/$slug': typeof LeadershipSlugRoute
  '/leadership/': typeof LeadershipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/cgi'
    | '/contact'
    | '/holdings'
    | '/leadership'
    | '/leadership/$slug'
    | '/leadership/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/cgi'
    | '/contact'
    | '/holdings'
    | '/leadership/$slug'
    | '/leadership'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/cgi'
    | '/contact'
    | '/holdings'
    | '/leadership'
    | '/leadership/$slug'
    | '/leadership/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  CgiRoute: typeof CgiRoute
  ContactRoute: typeof ContactRoute
  HoldingsRoute: typeof HoldingsRoute
  LeadershipRoute: typeof LeadershipRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgi': {
      id: '/cgi'
      path: '/cgi'
      fullPath: '/cgi'
      preLoaderRoute: typeof CgiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership/': {
      id: '/leadership/'
      path: '/'
      fullPath: '/leadership/'
      preLoaderRoute: typeof LeadershipIndexRouteImport
      parentRoute: typeof LeadershipRoute
    }
    '/leadership/$slug': {
      id: '/leadership/$slug'
      path: '/$slug'
      fullPath: '/leadership/$slug'
      preLoaderRoute: typeof LeadershipSlugRouteImport
      parentRoute: typeof LeadershipRoute
    }
  }
}

interface LeadershipRouteChildren {
  LeadershipSlugRoute: typeof LeadershipSlugRoute
  LeadershipIndexRoute: typeof LeadershipIndexRoute
}

const LeadershipRouteChildren: LeadershipRouteChildren = {
  LeadershipSlugRoute: LeadershipSlugRoute,
  LeadershipIndexRoute: LeadershipIndexRoute,
}

const LeadershipRouteWithChildren = LeadershipRoute._addFileChildren(
  LeadershipRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  CgiRoute: CgiRoute,
  ContactRoute: ContactRoute,
  HoldingsRoute: HoldingsRoute,
  LeadershipRoute: LeadershipRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
